import jwt from 'jsonwebtoken';
import { createRequire } from 'node:module';
const require=createRequire(import.meta.url);const {validateContent}=require('./validation.js');
const API='https://api.github.com';
export function json(data,status=200,headers={}){return new Response(JSON.stringify(data),{status,headers:{'content-type':'application/json; charset=utf-8',...headers}})}
export function corsHeaders(){const h={'access-control-allow-headers':'Content-Type, Authorization','access-control-allow-methods':'GET,POST,PUT,OPTIONS'};if(process.env.CORS_ORIGIN)h['access-control-allow-origin']=process.env.CORS_ORIGIN;return h}
export function auth(request){const h=request.headers.get('authorization')||'';const cookie=request.headers.get('cookie')||'';const token=h.startsWith('Bearer ')?h.slice(7):(cookie.match(/(?:^|;\s*)devsphere_session=([^;]+)/)?.[1]||'');try{return jwt.verify(token,process.env.JWT_SECRET)}catch{return null}}
export function sessionCookie(token){return `devsphere_session=${token}; Path=/; HttpOnly; ${process.env.VERCEL?'Secure; ':''}SameSite=Lax; Max-Age=28800`}
export function githubEnabled(){return Boolean(process.env.GITHUB_TOKEN&&process.env.GITHUB_OWNER&&process.env.GITHUB_REPO)}
async function gh(path,opts={}){const r=await fetch(API+path,{...opts,headers:{accept:'application/vnd.github+json',authorization:`Bearer ${process.env.GITHUB_TOKEN}`,'X-GitHub-Api-Version':'2022-11-28',...(opts.headers||{})}});const text=await r.text();let body;try{body=JSON.parse(text)}catch{body={message:text}}if(!r.ok)throw new Error(body.message||`GitHub API ${r.status}`);return body}
export async function githubFile(filePath){const branch=process.env.GITHUB_BRANCH||'main';return gh(`/repos/${process.env.GITHUB_OWNER}/${process.env.GITHUB_REPO}/contents/${filePath}?ref=${encodeURIComponent(branch)}`)}
export async function loadContent(){if(!githubEnabled()){const local=require('./data.js');return local}const file=await githubFile('server/data.js');const source=Buffer.from(file.content.replace(/\n/g,''),'base64').toString('utf8');const match=source.match(/module\.exports\s*=\s*([\s\S]*);\s*$/);if(!match)throw new Error('Invalid server/data.js format');const value=Function(`"use strict";return (${match[1]});`)();return validateContent(value)}
export async function saveContent(data){validateContent(data);if(!githubEnabled()){if(process.env.VERCEL)return {error:'Vercel CMS persistence requires GITHUB_OWNER, GITHUB_REPO and GITHUB_TOKEN'};const fs=require('node:fs');const path=require('node:path');fs.writeFileSync(path.join(process.cwd(),'server','data.js'),'module.exports = '+JSON.stringify(data,null,2)+';\n');return {persisted:'local-file'}}const file=await githubFile('server/data.js');const branch=process.env.GITHUB_BRANCH||'main';const body={message:'chore(cms): update DevSphere content',content:Buffer.from('module.exports = '+JSON.stringify(data,null,2)+';\n').toString('base64'),sha:file.sha,branch};const result=await gh(`/repos/${process.env.GITHUB_OWNER}/${process.env.GITHUB_REPO}/contents/server/data.js`,{method:'PUT',headers:{'content-type':'application/json'},body:JSON.stringify(body)});return {persisted:'github',commit:result.commit?.sha}}
export async function uploadAsset({filename,mime,base64,section}){if(!githubEnabled()){if(process.env.VERCEL)throw new Error('Vercel asset uploads require GitHub persistence variables');return {error:'Use local Express upload endpoint'}}const ext=filename.toLowerCase().match(/\.[a-z0-9]+$/)?.[0]||'';const allowedImage=['.png','.jpg','.jpeg','.webp','.svg'];const s=String(section||'site').replace(/[^a-z0-9_-]/gi,'').toLowerCase()||'site';if(s==='team'&&ext!=='.pdf'&&!allowedImage.includes(ext))throw new Error('Team uploads must be images or PDF');if(s!=='team'&&!allowedImage.includes(ext))throw new Error('Only image uploads are allowed here');const safe=String(filename).replace(/[^a-zA-Z0-9._-]/g,'-');const repoPath=`client/public/uploads/${s}/${Date.now()}-${safe}`;const branch=process.env.GITHUB_BRANCH||'main';const result=await gh(`/repos/${process.env.GITHUB_OWNER}/${process.env.GITHUB_REPO}/contents/${repoPath}`,{method:'PUT',headers:{'content-type':'application/json'},body:JSON.stringify({message:`chore(cms): upload ${safe}`,content:base64,branch})});const raw=`https://raw.githubusercontent.com/${process.env.GITHUB_OWNER}/${process.env.GITHUB_REPO}/${branch}/${repoPath}`;return {url:raw,persisted:'github',commit:result.commit?.sha}}
